# Configuración de servidores MCP
servers:
  # Servidor de sistema de archivos
  filesystem:
    class: mcp.mcp_servers.filesystem.FilesystemServer
    config:
      description: "Servidor MCP para acceso al sistema de archivos"
      root_path: "./data"
      allow_write: true
      auth_required: false
  
  # Servidor de eco para pruebas
  echo:
    class: examples.mcp.mcp_core_example.SimpleEchoServer
    config:
      description: "Servidor de eco para pruebas MCP"
      auth_required: false

# Configuración de clientes MCP
clients:
  # Cliente HTTP general
  http_client:
    class: mcp.connectors.http_client.MCPHttpClient
    config:
      timeout: 30
  
  # Cliente para servidores locales
  local_client:
    class: mcp.mcp_clients.local.LocalClient
    config:
      timeout: 5

# Configuración global
global:
  default_auth_token: "${MCP_AUTH_TOKEN}"
  server_port: 8080
  log_level: "INFO" 